async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 100
  size: 500
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 1
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_reports:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_base: ${GRAPHRAG_API_BASE}
    api_key: ${GRAPHRAG_API_KEY}
    model: text-embedding-ada-002
    type: openai_embedding
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  - specific object
  - abstract object
  max_gleanings: 1
  prompt: prompts/entity_extraction.txt
global_search:
  max_tokens: 12000
input:
  base_dir: ./
  file_encoding: utf-8
  file_pattern: .*\.txt
  file_type: text
  type: file
llm:
  api_base: ${GRAPHRAG_API_BASE}
  api_key: ${GRAPHRAG_API_KEY}
  max_tokens: 4000
  model: gpt-4o-mini
  model_supports_json: true
  type: openai_chat
local_search:
  community_prop: 0.1
  max_tokens: 12000
  text_unit_prop: 0.5
parallelization:
  stagger: 0.3
reporting:
  base_dir: report
  type: file
skip_workflows: []
snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false
storage:
  base_dir: /
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
çencoding_model: cl100k_base
